spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/tmt
      username: tmt
      password: toomanythoughts
      driver-class-name: org.postgresql.Driver
   flyway:
      baselineOnMigrate: true
      locations: classpath:db/migration
   jpa:
      hibernate:
         ddl-auto: update
      generate-ddl: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQL9Dialect
            jdbc:
               lob:
                  non_contextual_creation: true
   logging:
      level:
         org:
            hibernate:
            SQL: debug
            type:
               descriptor:
                  sql:
                     BasicBinder: TRACEll