spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/tmt
      username: tmt
      password: toomanythoughts
      driver-class-name: org.postgresql.Driver
   flyway:
      baselineOnMigrate: true
      locations: classpath:db/migration
   jpa:
      hibernate:
         ddl-auto: create
      generate-ddl: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQL10Dialect
            jdbc:
               lob:
                  non_contextual_creation: true
   logging:
      level:
         org:
            hibernate:
            SQL: debug
            type:
               descriptor:
                  sql:
                     BasicBinder: TRACEll
   main:
      allow-bean-definition-overriding: false
   messages:
      basename: i18n/messages
server:
   port: 8081
---
spring:
   profiles: test
   jpa:
      hibernate:
         ddl-auto: create-drop
---
spring:
   profiles: production
   jpa:
      hibernate:
         ddl-auto: none