spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tmt
    username: tmt
    password: toomanythoughts
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migrations
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  logging:
     level:
        org:
           hibernate:
           SQL: DEBUG
           type:
              descriptor:
                 sql:
                    BasicBinder: TRACEll
  security:
     filter:
        order: 0