spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tmt
    username: tmt
    password: toomanythoughts
  flyway:
    locations: classpath:db/migrations
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true